### ISSUE TITLE
Question on Usage

### ISSUE THREAD

**Issue by venkatsusarla** [cybertec-postgresql/ora_migrator#21]
Hello,

I am looking for options to speed the migration for a 1tb database, where only few tables are huge and I am intending to reduce the time of those tables by either using oracle_fdw or any other opensource oracle to postgres sync tool , which can help in capturing the delta data, which will reduce the total time of migration and so does the production downtime.

Came across this tool and was reading the document, could you please help in understanding the below queries which I have:
- Is it capable of migrating individual tables, rather than whole schema ?, apologize if I am missing anything in the document.
   Did see that, TABLE migration can be controlled through boolean attribute in PostgreSQL staging schema, is my understanding correct?
- Will oracle_migrate_refresh function help me to do incremental migration?, which will help me to sync Oracle and Postgres even when data is getting changed on source when I am doing migration?

Your answers would help me to decide my approach.

Regards,
Venkat

**Comment by laurenz** [comment]
Yes, you can migrate individual tables. Once you have created the foreign tables for the tables with `oracle_migrate_mkforeign`, you can migrate a single table's data with `oracle_materialize`.
This is useful for migrating several tables in parallel in concurrent sessions.

`oracle_migrate_refresh` only refreshes the data in the PostgreSQL staging schema with the current data in the Oracle database. It is useful if there are DDL changes in Oracle, but doesn't help with incremental migration.

Incremental migration is not easy. The best I can think of is creating triggers in Oracle that capture data changes, so that you can fetch and replay those changes in PostgreSQL. ora_migrator offers no support for that.

**Comment by venkatsusarla** [comment]
Thanks a lot for your response and feedback Laurenz.
