### ISSUE TITLE
Can we install ora_migrator in windows

### ISSUE THREAD

**Issue by puli06** [cybertec-postgresql/ora_migrator#28]
Hi 

Can we install this ora_migrator in Windows environment

**Comment by laurenz** [comment]
Sure, no problem.
Since it it only PL/pgSQL, it should be simple.
The harder part is installing oracle_fdw - either build the latest development version yourself or wait until I make a Windows binary release in fall.
For ora_migrator itself, all you need to do is copy the `*.sql` files and `ora_migrator.control` to the PostgreSQL extension directory.

**Comment by puli06** [comment]
Sure i will try to install.

Thank you
